ALTER TABLE member
  RENAME COLUMN nick_name TO nickname;

ALTER TABLE member
  ADD COLUMN gender      VARCHAR(10)                   DEFAULT 'MALE',
  ADD COLUMN updated_at  TIMESTAMP WITHOUT TIME ZONE    DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN birth_date  TIMESTAMP WITHOUT TIME ZONE    DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN created_at  TIMESTAMP WITHOUT TIME ZONE    DEFAULT CURRENT_TIMESTAMP;